### PR TITLE
Add pre-commit and lint files

### PR DESCRIPTION
**Pull request by jbampton**
Add codespell, markdownlint, misspell, prettier and yamllint

Fix spelling

https://pre-commit.com/
https://github.com/codespell-project/codespell
https://github.com/igorshubovych/markdownlint-cli
https://github.com/client9/misspell
https://prettier.io/
https://yamllint.readthedocs.io/en/stable/

### CODE REVIEW

**Comment by jbampton** [comment]
GitHub Actions don't run the first time they are added to a repository

**Comment by BaseMax** [comment]
Thank you John.
It's was very fantastic idea that stopped.

**Comment by BaseMax** [comment]
Merged, Hooray! ❤️

**Comment by jbampton** [comment]
Thank you !!

**Pull request merged**
